$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  output_folder:
    type: string
  bam_folder:
    type: string
  reference_folder:
    type: string
  refs_virus:
    type: string
required:
  - bam_folder
  - output_folder
  - reference_folder
  - refs_virus
